### ISSUE TITLE
choicequestion inside a tcolorbox or sth comparable

### ISSUE THREAD

**Issue by nichtleiter** [sdaps/sdaps-class#12]
Coming from sdaps 1.1.11 i have eventually dared to start looking into sdaps 1.9.2.

In the surveys i developed so far i rely heavily on `tcolorbox` to cluster the questions and make them visually more appealing.

Unfortunately the newest sdaps-class complains if a `choicequestion` environment is inside a `tcolorbox`. I looked into `sdapsclassic.cls` and found 
```
  \if_mode_vertical:
    % Nothing
  \else:
    \msg_error:nn { sdapsclassic } { choicequestion_wrong_mode }
  \fi:
```
to be responsible for that. After commenting it out everything worked as expected.

Maybe you have some ideas to make `sdaps-class` compatible with my `tcolorbox`-approach again. 

Best regards

**Comment by benzea** [comment]
Oh, I guess you are in inner vertical mode there.

Could you try the following:
```
  \if_mode_vertical:
    % Vertical mode is OK
  \else:
    \if_mode_inner:
      % inner vertical mode is OK
    \else:
      \msg_error:nn { sdapsclassic } { choicequestion_wrong_mode }
    \fi:
  \fi:
```

**Comment by nichtleiter** [comment]
I applied the changes but `choicequestion` still doesn't work inside `tcolorbox`.

I looked a bit deeper inside the code and figured out, that only the part 
```
  \if_mode_vertical:
    % Nothing
  \else:
    \msg_error:nn { sdapsclassic } { choicequestion_wrong_mode }
  \fi:
```
inside the definition of the control sequence `\_sdaps_classic_line_shipout_add:Nn` causes the problem. If the part (`sdapsclassic.cls`, line 575) is commented out the document compiles without any errors.

**Comment by benzea** [comment]
@nichtleiter, just to make sure, did you try updating the definition in \ _sdaps_classic_line_shipout_add:Nn?

**Comment by nichtleiter** [comment]
yes

**Comment by benzea** [comment]
Uh, I just tried it here. And sure, if that is commented out it compiles, but vertical mode is needed in this case because otherwise the question and answers will be typeset on a single line.

**Comment by benzea** [comment]
Closing. Assuming the workaround is correct as there has been no further messages.

Might be nice to document in some way though.
