### ISSUE TITLE
Get rid of "Draft" and Barcode in Pdf

### ISSUE THREAD

**Issue by pianoslum** [sdaps/sdaps-class#14]
Hi, thanks for the nice package.
However, I was unable to figure out, how to get rid of the "Draft" being written on the page and of the bar code.
I only want to use the packages to create a survey, I don't need the text-recognition thing.
I tried passing `final` and `no_questionnaire_id` as optional parameters to sdapsclassic but no success.
Is there a way to achieve this?

**Comment by benzea** [comment]
Ah, barcode … set the style to "custom", then the barcode will disappear.

**Comment by pianoslum** [comment]
Thanks for your quick reply! Your code works as intended, but unfortunately I don't know how to set the style to custom?

**Comment by benzea** [comment]
It is an option of the `sdapsclassic` class, i.e. `style=custom`, which just does `\tl_gset:Nn\g_sdaps_style_tl{custom}` internally.

**Comment by pianoslum** [comment]
I can confirm that this works - thanks a lot!
What about a "standalone"-option, that sets all these parameters, could that be an option?

**Comment by benzea** [comment]
Hmm, maybe `disable_recognition_marks`?

**Comment by pianoslum** [comment]
I thought that `standalone` could rid both the marks and the "draft".
It could also be split up in `disable_recognition_marks` and `final` :-)

**Comment by benzea** [comment]
Oh, that option would also get rid of the "`draft`" text! The "draft" text is solely there to denote the fact that the barcodes are just dummies. I don't see any reason to add the "draft" text if the goal isn't to use the SDAPS main program.

That said, `disable_recognition` is probably nicer as it is shorter.
