### ISSUE TITLE
Add sdaps to l3prefixes

### ISSUE THREAD

**Issue by pablgonz** [sdaps/sdaps-class#25]
Hi, could you add your packages to  latex3/l3kernel/doc/l3prefixes.csv.
Here's a link:

https://github.com/latex3/latex3/blob/master/l3kernel/doc/l3prefixes.csv

That file is for contact info, but also to keep track of the registered prefixes in packages to avoid that two packages use the same prefix and clash.

Thank you so much for creating sdaps, they're great :)
Greetings
Pablo

**Comment by benzea** [comment]
Done, see https://github.com/latex3/latex3/pull/674
