### ISSUE TITLE
Examples do not compile

### ISSUE THREAD

**Issue by ysalmon** [sdaps/sdaps-class#3]
I updated sdaps and sdaps-class to master and alas I cannot compile the examples given in this repo.
Here is what I get with a freshly updated texlive2017
```
[....omitted.....]
(/opt/yann/texlive/2017/texmf-dist/tex/generic/pgf/libraries/decorations/pgflib
rarydecorations.pathmorphing.code.tex))
\l__sdaps_tmpa_dim=\dimen192
\l__sdaps_tmpb_dim=\dimen193
\g__sdaps_qobject_id_int=\count271
\g_sdaps_linewidth_dim=\dimen194
\g__sdaps_checkbox_num_int=\count272
\g__sdaps_textbox_num_int=\count273
\l_sdaps_x_dim=\dimen195
\l_sdaps_y_dim=\dimen196
\l_sdaps_width_dim=\dimen197
\l_sdaps_height_dim=\dimen198
Runaway argument?
{
! Forbidden control sequence found while scanning use of \iow_open:Nn.
<inserted text> 
                \par 
l.512 ...Nn \g_sdaps_infofile_iow { \c_job_name_tl
                                                   . sdaps } 
```

**Comment by benzea** [comment]
Hmm, what file are you compiling right now?

**Comment by ysalmon** [comment]
I can compile my usual files, with XeLaTeX. They rely on scrartcl, tikz, listings, and so on.

**Comment by ysalmon** [comment]
Letting XeLaTeX go further into your document (interactive compilation with "x" when an error occurs) leads to the following message
```
The deprecated command '\c_job_name_tl' has been or will be removed on
! 2017-01-01. Use instead '\c_sys_jobname_str
```

**Comment by benzea** [comment]
Oha! Seems like you have a newer version of the libraries than I do. Indeed \c_sys_jobname_str is more sensible (i.e. a string instead of token list).

Let's commit a fix for that.

**Comment by ysalmon** [comment]
Now autocross_countsheet.tex compiles but arraydemo.tex does not, with
```
\g__sdaps_array_info_iow=\write6
\openout6 = `questionnaire.sdapsarraytoc'.

\g__file_internal_ior=\read3
\openout6 = `questionnaire.sdapsarraytic'.

! Missing } inserted.
<inserted text> 
                }
l.56    \begin{sdapsarray}
```

**Comment by benzea** [comment]
Hmm? I changed all of these cases to use \ c_sys_jobname_str (sorry for forgetting to mention you in the commit).

Do you have any idea what might be causing it at this point? Unfortunately it runs fine here /me checks if there is a new TeXLive available in debian unstable.

**Comment by benzea** [comment]
Ah, there is a new version, I'll try to install that and see if I can reproduce the issue then.

**Comment by benzea** [comment]
btw. unfortunately none of the (public) examples actually show use all the different features. But I guess that http://sdaps.org/class-doc/sdapsclassic.html still gives quite a good initial overview of what is possible.

**Comment by benzea** [comment]
Interesting, I simply forgot a place (pushing a fix now), but that shouldn't really have caused an issue in this case.

**Comment by ysalmon** [comment]
BTW you forgot some c_job_name_tl in sdapsclassic (see #4 )

**Comment by benzea** [comment]
Yeah I noticed that. But there is another issue that I apparently used hbox_set:Nn/vbox_set:Nn wrongly and I need to fix this (there were a few mails on latex-l about this some time ago).

**Comment by benzea** [comment]
*sigh* I give up for now.

The issue is mentioned in this thread:
 https://listserv.uni-heidelberg.de/cgi-bin/wa?A2=ind1706&L=LATEX-L&F=&S=&P=71

But I don't really get the solution right now. Also, the required commands do not even exist for all relevant macros. Also somewhat bad is that I would need to do a version switch if support for slightly older TeXlive versions is desired.

**Comment by ysalmon** [comment]
Is this relevant : https://tex.stackexchange.com/questions/377244/tl2017-broke-my-boxes ?

Could you provide a branch or a tag to a commit that does not use the involved features ? Where is the old sdaps class ?

**Comment by ysalmon** [comment]
Nevermind ; the old class was in the sdaps repo and last exists at commit https://github.com/sdaps/sdaps/commit//4781de5a2867ee4b1b6aaae6f4bd043b589543fe

**Comment by benzea** [comment]
Oh, yes. Just check out the "stable" branch from the old repository for the old class!

**Comment by benzea** [comment]
Yes, the stackexchange question is exactly the issue. However I am not quite sure how to properly fix it yet. The afterassignment sounds somewhat promising though I am thinking that the `\[vh]box_set_end:` commands should quite likely also work.

**Comment by ysalmon** [comment]
Yes, it seems that to begin a box in one command and finish it in another one, ```\hbox_set:Nw \mybox ....... \hbox_set_end``` is de mode. One needs to know which of the ```\egroup```s in the code are terminating an hbox.

There is also a [```\vbox_set_top:Nn``` with a ```\bgroup```](https://github.com/sdaps/sdaps-class/blob/master/sdapsarray.dtx#L467) but the LaTeX3 documentation from July the 21th does not state the existence of a ```\vbox_set_top:Nw```. So, should it remain as it is for now ?

**Comment by benzea** [comment]
To be honest, I am inclined to port it to use plain TeX for a start and then figure out how to do it properly. That should be safe for a start and then one can switch it once everyone should have TeXlive late 2017 early 2018 with all the features.

Other than that, I need to go back to Joseph Wright about this. I kind of fear that the code overall is a bit too crazy so it might take some time to explain it (he was asking why I need a \vbox_set_top:Nw version) …

**Comment by ysalmon** [comment]
Indeed, the code of sdapsarray seems very complicated to me, much more than the old sdaps class. At first I thought it was because of LaTeX3, which I do not know (but I am not a great LaTeX2 expert either). But I read the basic LaTeX3 documentation and the new naming conventions make things actually clearer once you know them.

No, the code is conceptually more involved. It seems you are trying to allow a matrix of checkboxes to span automatically over several pages. This roughly amount to reimplementing the longtable package.

BTW, I do not see an obvious use case for this (but I confess I am not using sdaps for its original purpose) : is the questions are not related, there would probably be several matrices to begin with ; if all questions are related, having the answer matrix span over many pages seems error-prone for the user ; if it only spans two pages, maybe users would be fine with tuning this by hand as an interim solution.

**Comment by benzea** [comment]
The majority of the complexity arises from the fact that I am trying to allow the usage of fragile content. i.e. I want people to  be able place e.g. a \verb inside a question text (after specifying an alternative text for the metadata). This was a big pain point in the old class even though many users may never see those issues.

Another t thing that complicates it quite a lot is the possibility to exchange rows and columns (i.e. put questions into columns). This was a feature request from the community and doing it like this has a number of other advantages even if it is a little bit over-engineered (e.g. metadata generation gets a lot simpler).

**Comment by benzea** [comment]
PS: I am pretty sure that I have looked at alternatives. But I think none of them could

**Comment by ysalmon** [comment]
That's what I thought but did not write -- I was clarifying my post as you were answering.

**Comment by ysalmon** [comment]
Yes, verb ans listings in some contexts are painful. In those case, I typeset the listing in a box before entering the structure and then ```\box\mybox``` at the actual place but it it is cumbersome and I do not know if this can be automated. And this becomes horrendously tricky if you want to manage line-breaking et variable column width…

**Comment by benzea** [comment]
`\verb` needs to modify the low level parser of TeX. This is why these commands can never be a parameter to a macro (which is the reason for the \bgroup \let\next= trick).

**Comment by benzea** [comment]
Oh, btw. the "sdapsarray" package is entirely easily separable from the rest of SDAPS. Basically all one would need to do is find another name for it and put it on CTAN.

**Comment by benzea** [comment]
Alright, this is fixed for now. Still need to follow up so that the missing macro is added upstream, but this just makes the code a bit more beautiful really.
